version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aicademy_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Application Configuration
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL}
      - API_KEY=${API_KEY}

      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRES_SECONDS=${JWT_ACCESS_EXPIRES_SECONDS}
      - JWT_REFRESH_EXPIRES_SECONDS=${JWT_REFRESH_EXPIRES_SECONDS}
      
      # Database Configuration
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      
      # Server Configuration
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_RELOAD=${SERVER_RELOAD}
      - SERVER_LOG_LEVEL=${SERVER_LOG_LEVEL}
      
      # CORS Configuration
      - CORS_ORIGINS=${CORS_ORIGINS}
      - CORS_METHODS=${CORS_METHODS}
      - CORS_HEADERS=${CORS_HEADERS}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS}
    depends_on:
      - mysql_db
    volumes:
      - ./logs:/app/logs
      - ./app:/app/app
      - ./database:/app/database

  mysql_db:
    image: mysql:8.0
    container_name: AIcademy_database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password


# Volumes
volumes:
  mysql_data:
    driver: local
