version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: AIcademy_database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password

  app:
    depends_on:
      - mysql_db

volumes:
  mysql_data:
    driver: local
