name: Build, Lint, and Deploy

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run black
        run: |
          black .

      - name: Run flake8
        run: |
          # Fail if critical errors
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Warnings only (exit-zero makes it non-blocking)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

  deploy_staging:
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            cd AIcademy
            git checkout develop
            git pull
            docker compose down || true
            docker compose up --build

      - name: Run migrations
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            cd AIcademy
            docker compose exec -T aicademy_be make migration_run
            docker compose exec -T aicademy_be make seed
